FROM node:20-alpine

WORKDIR /app

RUN addgroup -S nodejs -g 1001 && adduser -S nextjs -u 1001 -G nodejs

COPY package.json yarn.lock* pnpm-lock.yaml* ./
COPY prisma ./prisma/

RUN rm -rf node_modules && \
  if [ -f yarn.lock ]; then yarn install --frozen-lockfile --force; \
  elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install --frozen-lockfile --force; \
  else npm install --immutable --force; \
  fi

RUN chown -R nextjs:nodejs /app

USER nextjs

RUN npx prisma generate
